import './usecases/createPhoto'
import './usecases/createUsuario'
import './usecases/deleteUsuario'
import './usecases/getMedicos'
import './usecases/getUsuarios'
import './usecases/updateUserRol'
import './usecases/updateUsuario'
