import './usecases/createPacienteBeneficiario'
import './usecases/createPacienteTrabajador'
import './usecases/deletePaciente'
import './usecases/getPacientes'
import './usecases/getTrabajadores'
import './usecases/updatePacienteBeneficiario'
import './usecases/updatePacienteTrabajador'
